//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Plan_postavki
    {
        public int Id_plana_postavki { get; set; }
        public int Id_postavshika { get; set; }
        public Nullable<int> Id_lekarstva { get; set; }
        public int Kolichestvo { get; set; }
    
        public virtual Lekarstvo Lekarstvo { get; set; }
        public virtual Postavshik Postavshik { get; set; }
    }
}
