//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Plan_lecheniya
    {
        public int Id_plana_lecheniya { get; set; }
        public Nullable<int> Dlitelnost_primeneniya { get; set; }
        public int Id_diagnoza { get; set; }
        public Nullable<int> Id_lekarstva { get; set; }
    
        public virtual Diagnoz Diagnoz { get; set; }
        public virtual Lekarstvo Lekarstvo { get; set; }
    }
}
