//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_MedicineSuppliers
    {
        public int ID_Лекарства { get; set; }
        public string Название_лекарства { get; set; }
        public string Поставщик { get; set; }
        public Nullable<int> Количество { get; set; }
    }
}
