//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vipiska
    {
        public int Id_vipiski { get; set; }
        public System.DateTime Date { get; set; }
        public int Id_medcard { get; set; }
        public Nullable<int> id_prichiny_vipiski { get; set; }
    
        public virtual Med_card Med_card { get; set; }
        public virtual Prichina_vypiski Prichina_vypiski { get; set; }
    }
}
