//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_DoctorPatients
    {
        public int ID_Врача { get; set; }
        public string ФИО_Врача { get; set; }
        public Nullable<int> Номер_медкарты { get; set; }
        public string Фамилия_пациента { get; set; }
        public string Имя_пациента { get; set; }
        public string Отчество_пациента { get; set; }
    }
}
