//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_PalataStatus
    {
        public int Номер_палаты { get; set; }
        public Nullable<int> Этаж { get; set; }
        public string Пол { get; set; }
        public Nullable<int> Общее_количество_коек { get; set; }
        public Nullable<int> Занятые_койки { get; set; }
        public Nullable<int> Свободные_койки { get; set; }
    }
}
